const bloodDoners = [
  {
    name: "Labib",
    age: 23,
    address: "kishoreganj",
    cellNumber: "0191986188",
    bloodGroup: "O-",
    isMarried: true,
    lastDonateBloodDate: 340,
    weight: 57,
    gender: "male",
  },
  {
    name: "Roja",
    age: 19,
    address: "kishoreganj",
    cellNumber: "01433986188",
    bloodGroup: "O",
    isMarried: true,
    lastDonateBloodDate: 110,
    weight: 45,
    gender: "female",
  },
  {
    name: "Halal",
    age: 47,
    address: "kishoreganj",
    cellNumber: "0191986188",
    bloodGroup: "A+",
    isMarried: false,
    lastDonateBloodDate: 40,
    weight: 45,
    gender: "male",
  },
];
